apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    fint.role: consumer
    fint.stack: administrasjon-personal
  name: consumer-administrasjon-personal
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080
  selector:
    fint.role: consumer
    fint.stack: administrasjon-personal
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    fint.role: provider
    fint.stack: administrasjon-personal
  name: provider-administrasjon-personal
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080
  selector:
    fint.role: provider
    fint.stack: administrasjon-personal
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    fint.role: consumer
    fint.stack: administrasjon-personal
  name: consumer-administrasjon-personal
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      fint.role: consumer
      fint.stack: administrasjon-personal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        fint.role: consumer
        fint.stack: administrasjon-personal
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Oslo
        - name: JAVA_TOOL_OPTIONS
          value: -XX:+ExitOnOutOfMemoryError -Xmx6G -verbose:gc
        - name: fint.audit.mongo.databasename
          value: fint-audit
        - name: fint.audit.mongo.connection-string
          valueFrom:
            secretKeyRef:
              key: mongodb
              name: fint-audit
        - name: fint.cache.manager
          value: default
        - name: fint.events.orgIds
          value: health.fintlabs.no
        - name: fint.hazelcast.kubernetes.enabled
          value: "true"
        - name: fint.hazelcast.kubernetes.namespace
          value: default
        - name: fint.hazelcast.kubernetes.labelName
          value: fint.stack
        - name: fint.hazelcast.kubernetes.labelValue
          value: administrasjon-personal
        - name: fint.relations.default-base-url
          value: https://api.felleskomponent.no
        - name: server.context-path
          value: /administrasjon/personal
        image: fint/consumer-personal:3.6.3
        imagePullPolicy: IfNotPresent
        name: consumer-administrasjon-personal
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /administrasjon/personal/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: 250m
            memory: 6Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    fint.role: provider
    fint.stack: administrasjon-personal
  name: provider-administrasjon-personal
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      fint.role: provider
      fint.stack: administrasjon-personal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        fint.role: provider
        fint.stack: administrasjon-personal
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Oslo
        - name: JAVA_TOOL_OPTIONS
          value: -XX:+ExitOnOutOfMemoryError -Xmx3G -verbose:gc
        - name: fint.audit.mongo.databasename
          value: fint-audit
        - name: fint.audit.mongo.connection-string
          valueFrom:
            secretKeyRef:
              key: mongodb
              name: fint-audit
        - name: fint.events.orgIds
          value: health.fintlabs.no
        - name: fint.hazelcast.kubernetes.enabled
          value: "true"
        - name: fint.hazelcast.kubernetes.namespace
          value: default
        - name: fint.hazelcast.kubernetes.labelName
          value: fint.stack
        - name: fint.hazelcast.kubernetes.labelValue
          value: administrasjon-personal
        - name: fint.provider.assets.endpoint
          value: https://admin.fintlabs.no/api/components/assets/administrasjon_personal
        - name: fint.provider.max-number-of-emitters
          value: "5"
        - name: server.context-path
          value: /administrasjon/personal/provider
        - name: server.tomcat.max-threads
          value: '400'
        - name: server.tomcat.max-connections
          value: '20000'
        image: fintlabs.azurecr.io/provider:2.1.0
        imagePullPolicy: IfNotPresent
        name: provider-administrasjon-personal
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /administrasjon/personal/provider/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 3Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
