apiVersion: v1
kind: Service
metadata:
  annotations: {service.beta.kubernetes.io/azure-load-balancer-internal: 'true'}
  labels: {fint.stack: administrasjon-personal, fint.role: consumer}
  name: consumer-administrasjon-personal
spec:
  type: LoadBalancer
  ports:
    - {name: '8080', port: 8080}
  selector: {fint.stack: administrasjon-personal, fint.role: consumer}
---
apiVersion: v1
kind: Service
metadata:
  annotations: {service.beta.kubernetes.io/azure-load-balancer-internal: 'true'}
  labels: {fint.stack: administrasjon-personal, fint.role: provider}
  name: provider-administrasjon-personal
spec:
  type: LoadBalancer
  ports:
    - {name: '8080', port: 8080}
  selector: {fint.stack: administrasjon-personal, fint.role: provider}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {fint.stack: administrasjon-personal, fint.role: consumer}
  name: consumer-administrasjon-personal
spec:
  replicas: 1
  selector:
    matchLabels: {fint.stack: administrasjon-personal, fint.role: consumer}
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
  template:
    metadata:
      labels: {fint.stack: administrasjon-personal, fint.role: consumer}
    spec:
      containers:
        - name: consumer-administrasjon-personal
          image: fintlabs.azurecr.io/consumer-administrasjon-personal:PR-16.9
          envFrom:
            - configMapRef:
                name: fint-environment
            - secretRef:
                name: fint-events-azure-eventhub
          env:
            - {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -XX:+UseG1GC -Xmx8G -verbose:gc'}
            - {name: fint.hazelcast.kubernetes.enabled, value: 'true'}
            - {name: fint.hazelcast.kubernetes.namespace, value: default}
            - {name: fint.hazelcast.kubernetes.labelName, value: fint.stack}
            - {name: fint.hazelcast.kubernetes.labelValue, value: administrasjon-personal}
            - {name: fint.cache.packer, value: DEFLATE}
            - {name: fint.consumer.cache.disabled.variabellonn, value: "true"}
            - {name: fint.consumer.cache.disabled.fastlonn, value: "true"}
            - {name: fint.consumer.cache.disabled.fasttillegg, value: "true"}
            - {name: fint.consumer.cache.disabled.fravar, value: "true"}
            - {name: fint.consumer.cache.disabled.personalmappe, value: "true"}
            - {name: server.context-path, value: /administrasjon/personal}
            - {name: logging.level.no.fint.audit.plugin.eventhub, value: debug}
          ports:
            - {containerPort: 8080}
          readinessProbe:
            httpGet: {path: /administrasjon/personal/health, port: 8080}
            initialDelaySeconds: 60
            timeoutSeconds: 30
          resources:
            requests: {memory: 4Gi, cpu: 250m}
            limits: {memory: 8Gi, cpu: '2'}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {fint.stack: administrasjon-personal, fint.role: provider}
  name: provider-administrasjon-personal
spec:
  replicas: 1
  selector:
    matchLabels: {fint.stack: administrasjon-personal, fint.role: provider}
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
  template:
    metadata:
      labels: {fint.stack: administrasjon-personal, fint.role: provider}
    spec:
      containers:
        - name: provider-administrasjon-personal
          image: fintlabs.azurecr.io/provider:PR-40.8
          envFrom:
            - configMapRef:
                name: fint-environment
            - secretRef:
                name: fint-events-azure-eventhub
          env:
            - {name: fint.hazelcast.kubernetes.enabled, value: 'true'}
            - {name: fint.hazelcast.kubernetes.namespace, value: default}
            - {name: fint.hazelcast.kubernetes.labelName, value: fint.stack}
            - {name: fint.hazelcast.kubernetes.labelValue, value: administrasjon-personal}
            - {name: fint.provider.assets.endpoint, value: 'https://admin-beta.fintlabs.no/api/components/assets/administrasjon_personal'}
            - {name: fint.provider.max-number-of-emitters, value: '5'}
            - {name: fint.provider.sse.heartbeat.enabled, value: 'true'}
            - {name: server.context-path, value: /administrasjon/personal/provider}
            - {name: server.tomcat.max-threads, value: '400'}
            - {name: server.tomcat.max-connections, value: '30000'}
            - {name: logging.level.no.fint.audit.plugin.eventhub, value: debug}
          ports:
            - {containerPort: 8080}
          readinessProbe:
            httpGet: {path: /administrasjon/personal/provider/health, port: 8080}
            initialDelaySeconds: 60
            timeoutSeconds: 30
          resources:
            requests: {memory: 1Gi, cpu: 250m}
            limits: {memory: 3Gi, cpu: 2000m}
      restartPolicy: Always
