springfox:
 title: 'FINT Consumer Personal'
 version: '@version@'

event-model-version: '@eventModelVersion@'
personal-model-version: '@personalModelVersion@'
relation-model-version: '@relationModelVersion@'
