fint:
 events:
  test-mode: true

 audit:
  test-mode: true

 relations:
  force-https: false

 consumer:
  cache:
   initialDelay:
    arbeidsforhold: 1000
    person: 2000
    personalressurs: 3000

link-mapper-base-url: http://localhost:8080