spring:
  application:
    name: fint-consumer-administrasjon-personal

fint:
 events:
  orgIds: mock.no
  test-mode: true
  queue-endpoint-enabled: true

  audit:
    test-mode: true

  relations:
    force-https: false
    default-base-url: /

  hazelcast:
    members: localhost

  consumer:
    test-mode: true

server:
  context-path: ""
  port: 8080

endpoints:
  sensitive: false

management:
  security:
    enabled: false
