springfox:
 title: 'FINT Consumer Personal'
 version: '@version@'

event-model-version: '@eventModelVersion@'
administrasjon-model-version: '@administrasjonModelVersion@'
relation-model-version: '@relationModelVersion@'
